# Generated by Django 4.0.4 on 2022-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings_comments_bids_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='listings',
            name='starting_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
