# Generated by Django 4.0.4 on 2022-05-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bids_bid_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='current_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='type',
            field=models.CharField(default='BID', max_length=16),
        ),
    ]
