# Generated by Django 4.0.4 on 2022-05-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_starting_bid_listing_current_bid_bid_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='type',
            new_name='bid_type',
        ),
    ]
