# Generated by Django 4.0.4 on 2022-05-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_amount_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.bid'),
        ),
    ]
